plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
defaults:
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
title: Ferticidio's
description: Probando github pages
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
